[project]
name = "renardo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Elie Gavoty", email = "mail@eliegavoty.fr" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
renardo = "renardo:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
