[build-system]
requires = ["uv", "hatchling"]
build-backend = "hatchling.build"

[project]
name = "renardo"
version = "1.0.0.dev14"
description = "Python livecoding environment - New fork of FoxDot"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    {name = "Elie Gavoty", email = "eliegavoty@free.fr"}
]
license = {text = "GPL-3.0"}
dependencies = [
    "midiutil",
    "tomli",
    "tomli-w",
    "requests",
    "psutil",
    "indexed",
    "python-rtmidi",
    "ttkbootstrap",
    "textual",
    "python-reapy"
]

[project.scripts]
renardo = "renardo:main"

[project.urls]
Homepage = "http://renardo.org/"