name: Upload Python Package

#on: # only triggered on manuel release creation
#  release:
#    types: [published]

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:

  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      # useless to create prerelease for each dev version but usefull to push to pypi
      
      # - name: Create prerelease
      #  if: contains( github.ref_name, 'dev' ) && startsWith( github.ref_name, 'v')
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    tag: ${{ github.ref_name }}
      #  run: |
      #    gh release create "$tag" \
      #       --repo="$GITHUB_REPOSITORY" \
      #       --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
      #       --generate-notes \
      #       --prerelease

      - name: Create release
        if: (false == contains( github.ref_name, 'dev' )) && startsWith( github.ref_name, 'v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
             --repo="$GITHUB_REPOSITORY" \
             --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
             --generate-notes \

      
  pypi-publish-renardo-gatherer:
    runs-on: ubuntu-latest
    environment:
      name: release 
      url: https://pypi.org/p/renardo
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: |
          cd renardo_gatherer
          python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          #password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: renardo_gatherer/dist/
          skip-existing: true

  pypi-publish-renardo-lib:
    runs-on: ubuntu-latest
    environment:
      name: release 
      url: https://pypi.org/p/renardo
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: |
          cd renardo_lib
          python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          #password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: renardo_lib/dist/
          skip-existing: true
  
  pypi-publish-foxdot-editor:
    runs-on: ubuntu-latest
    environment:
      name: release 
      url: https://pypi.org/p/renardo
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: |
          cd FoxDotEditor
          python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          #password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: FoxDotEditor/dist/
          skip-existing: true
  
  pypi-publish-renardo:
    runs-on: ubuntu-latest
    environment:
      name: release 
      url: https://pypi.org/p/renardo
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: |
          cd renardo
          python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          #password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: renardo/dist/
          skip-existing: true